# -*- coding: utf-8 -*-
"""Entregable 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrYLE3jYwoRhDcByZvT_nvKO6QglQOt9
"""



"""# Mi Primer Notebook de Ciencia de Datos"""

import numpy as np
print("Versión de NumPy:", np.__version__)

import numpy as np
arr = np.random.randint(1, 51, 15)
print("Array:", arr)
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))

import numpy as np
matriz = np.random.randint(1, 16, size=(4, 4))
print("Matriz de 4x4:")
print(matriz)
print(" ")
print("Matriz seleccionada")
print(matriz[2:, :2])

import pandas as pdx
diccionario = {"Nombre": ["Ana", "Luis", "Marta", "Juan"], "Edad": [28, 34, 45, 23], "Ciudad": ["Madrid", "Bogotá", "Lima", "México DF"] }
df = pdx.DataFrame(diccionario)
print(df)

df = pdx.read_csv("Iris.csv")
print(df)

df = pdx.read_csv("Iris.csv")
print("Primeras 10 filas")
print(df.head(10))
print(" ")
print("Información general")
print(df.info())
print(" ")
print("Resumen estadístico")
print(df.describe())

import pandas as pdx
diccionario = {"Nombre": ["Ana", "Luis", "Marta", "Juan"], "Edad": [28, 34, 45, 23], "Ciudad": ["Madrid", "Bogotá", "Lima", "México DF"] }
df = pdx.DataFrame(diccionario)
print("Edad")
print(df["Edad"])
print("")
print("Columna edad")
print(df["Edad"])
print("")
print("Mayores de 30")
print(df[df["Edad"]>30])